# Generated by Django 2.0.3 on 2018-12-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contains',
            field=models.TextField(max_length=255),
        ),
    ]
