# Generated by Django 2.0.13 on 2019-06-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190630_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
